language: go
sudo: false

notifications:
  slack:
    rooms:
      - blend:wni8iXGkdYpw6JTIH0V8o4Fq#connectivity-devs
    on_success: always
    on_failure: always

before_script:
  - go get -u github.com/blendlabs/go-assert
  - go get -u github.com/blendlabs/go-exception

script: 
  - go test
